# Generated by Django 5.0.6 on 2024-06-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_fname_alter_user_lname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dial_code', models.CharField(max_length=4)),
                ('mobile_number', models.PositiveIntegerField()),
                ('isActive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mobilenumber_users',
            },
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box1', models.IntegerField()),
                ('box2', models.IntegerField()),
                ('box3', models.IntegerField()),
                ('box4', models.IntegerField()),
                ('isActive', models.BooleanField(default=False)),
                ('resend_otp', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'otp_users',
            },
        ),
    ]
