# Generated by Django 5.0.6 on 2024-07-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_mobilenumber_rename_box1_otp_otp_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
