# Generated by Django 5.0.6 on 2024-07-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='resend_otp',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
