# Generated by Django 5.0.6 on 2024-07-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userprofile_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ('created_on',)},
        ),
        migrations.AddField(
            model_name='otp',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
