# Generated by Django 5.0.6 on 2024-07-15 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_otp_options_otp_created_on_otp_isdelete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('isDelete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256)),
                ('address', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('isDefault', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'useraddress_users',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.useraddress'),
        ),
    ]
