# Generated by Django 5.0.6 on 2024-07-16 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_useraddress_city_useraddress_district_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ('name',), 'verbose_name_plural': 'User adresses'},
        ),
    ]
