# Generated by Django 5.0.6 on 2024-07-17 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_useraddress_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_address',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
