# Generated by Django 5.0.6 on 2024-06-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('furniture', 'Furniture')], max_length=255)),
            ],
            options={
                'db_table': 'product_products',
                'ordering': ('name',),
            },
        ),
    ]
