# Generated by Django 5.0.6 on 2024-06-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_color_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('furniture', 'Furniture'), ('fashion', 'Fashion'), ('kitchenware', 'Kitchenware'), ('ornaments', 'Ornaments'), ('perfumes', 'Perfumes'), ('watches', 'Watch')], max_length=255),
        ),
    ]
