# Generated by Django 5.0.6 on 2024-06-28 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='dialshape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.dialshape'),
        ),
    ]
