# Generated by Django 5.0.6 on 2024-06-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_dialshape_product_dialshape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialshape',
            name='shape',
            field=models.CharField(choices=[('round', 'Round'), ('square', 'Square')], max_length=100),
        ),
    ]
