# Generated by Django 5.0.6 on 2024-06-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_dialshape_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialshape',
            name='watchcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dialshape',
            name='shape',
            field=models.CharField(max_length=100),
        ),
    ]
