# Generated by Django 5.0.6 on 2024-06-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_dialshape_watchcategory_alter_dialshape_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dialshape',
        ),
        migrations.AddField(
            model_name='product',
            name='dialshape',
            field=models.ManyToManyField(blank=True, null=True, to='products.dialshape'),
        ),
    ]
