# Generated by Django 5.0.6 on 2024-06-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
