# Generated by Django 5.0.6 on 2024-06-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('furniture', 'Furniture'), ('fashion', 'Fashion'), ('kitchenware', 'Kitchenware'), ('ornaments', 'Ornaments'), ('perfumes', 'Perfumes'), ('watches', 'Watch')], max_length=255, null=True),
        ),
    ]
