# Generated by Django 5.0.6 on 2024-07-01 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_subcategory_rename_name_product_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='category_products',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='subcategory_products',
        ),
    ]
