# Generated by Django 5.0.6 on 2024-07-01 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
