# Generated by Django 5.0.6 on 2024-07-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_subcategory_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('category',)},
        ),
        migrations.AddField(
            model_name='product',
            name='top_product',
            field=models.BooleanField(default=False),
        ),
    ]
