# Generated by Django 5.0.6 on 2024-07-01 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_product_options_product_top_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category_name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('name',), 'verbose_name_plural': 'Subcategories'},
        ),
    ]
