# Generated by Django 5.0.6 on 2024-07-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_available_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature',
            field=models.ManyToManyField(to='products.feature'),
        ),
    ]
