# Generated by Django 5.0.6 on 2024-07-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_remove_product_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='original_price',
        ),
    ]
