# Generated by Django 5.0.6 on 2024-07-05 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_userwishlist_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwishlist',
            name='userprofile',
        ),
    ]
