# Generated by Django 5.0.6 on 2024-07-05 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_userwishlist_options_userwishlist_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userwishlist',
            options={},
        ),
        migrations.RemoveField(
            model_name='userwishlist',
            name='userprofile',
        ),
    ]
