# Generated by Django 5.0.6 on 2024-07-05 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_userwishlist_options_and_more'),
        ('users', '0009_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwishlist',
            name='userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
